- name: Create docker compose for elastic_master
  hosts: elastic
  become: yes
  gather_facts: true
  tasks:
    - name: Get list elasticsearch node
      set_fact:
        hostname_nodes: "{{ groups['elastic'] | map('extract', hostvars, ['ansible_hostname']) | list }}"

    - name: Copy env file
      copy: 
        src: /root/elastic-kibana-ansible/.env
        dest: /root/elastic_kibana_lab/.env
        mode: 0664  # Optional: Set the permissions of the file
    - name: Create docker compose for master
      template:
        src: docker-compose-elastic.yml.j2
        dest: /root/elastic_kibana_lab/docker-compose.yml
        mode: 0644

- name: Start service elastic
  hosts: elastic
  become: yes
  tasks:
    - name: Stop service before start
      community.docker.docker_compose:
        project_src: /root/elastic_kibana_lab
        build: false
        remove_volumes: yes
        state : absent  # the same running docker-compose down

    - name: Start service
      community.docker.docker_compose:
        project_src: /root/elastic_kibana_lab
        build: false
        state : present # the same running docker-compose up



- name: Copy files to elastic
  hosts: all
  become: yes
  gather_facts: false
  tasks:      
    - name: Copy file cert to all hosts
      copy:
        src: /root/ca_files/
        dest: /var/lib/docker/volumes/elastic_kibana_lab_certs/_data/

- name: Change password for kibana_system user
  hosts: elastic
  become: yes
  vars:
    containers_need_restart:
      - elastic
  tasks:
    - name: Restart container elastic
      community.docker.docker_container:
        name: "{{ item }}"
        restart: true
      with_items: "{{ containers_need_restart }}"

    - name: Wait for cURL response
      environment:
        SSL_CERT_FILE: "/var/lib/docker/volumes/elastic_kibana_lab_certs/_data/ca/ca.crt"
      uri:
        url: "https://{{ ansible_ssh_host }}:9200/"
        method: GET
        validate_certs: no
        user: "elastic"
        password: "vuotnh"
        force_basic_auth: yes
      register: curl_output
      until: curl_output.status == 200
      retries: 10
      delay: 5

    - name: Change password kibana_system
      uri:
        url: https://{{ ansible_ssh_host }}:9200/_security/user/kibana_system/_password
        method: POST
        validate_certs: no
        body_format: json
        body:
          password: "vuotnh"
        headers:
          Content-Type: "application/json"
        user: "elastic"
        password: "vuotnh"
        force_basic_auth: no
        client_cert: /var/lib/docker/volumes/elastic_kibana_lab_certs/_data/ca/ca.crt
        client_key: /var/lib/docker/volumes/elastic_kibana_lab_certs/_data/ca/ca.key