- name: Deploy ha_kibana
  hosts: kibana
  become: yes
  gather_facts: true
  tasks:
    - name: Create /root/elastic_kibana_lab directory
      file:
        path: /root/elastic_kibana_lab/haproxy
        state: directory
        mode: 0755
    - name: Create keepalived directory
      file:
        path: /root/elastic_kibana_lab/keepalived
        state: directory
        mode: 0755

    - name: Create haproxy config file
      template:
        src: haproxy.cfg.j2
        dest: /root/elastic_kibana_lab/haproxy/haproxy.cfg
        mode: 0644

    - name: Copy pem file for haproxy
      copy: 
        src: /root/elastic-kibana-ansible/haproxy.pem
        dest: /root/elastic_kibana_lab/haproxy/haproxy.pem
        owner: root  # Optional: Set the owner of the file
        mode: 0644  # Optional: Set the permissions of the file

    - name: Copy env file
      copy: 
        src: /root/elastic-kibana-ansible/.env
        dest: /root/elastic_kibana_lab/.env
        mode: 0664  # Optional: Set the permissions of the file
      
    - name: Copy check_tcp file
      copy: 
        src: /root/elastic-kibana-ansible/check_tcp.sh
        dest: /root/elastic_kibana_lab/keepalived/check_tcp.sh
        mode: 0645  # Optional: Set the permissions of the file

    - name: Get interface name based on IP address
      set_fact:
        interface_name: "{{ ansible_default_ipv4.interface }}"
      when: ansible_default_ipv4.address == '{{ ansible_ssh_host }}'
    - name: Print the interface name
      debug:
        var: interface_name

    - name: Create keepalived config file
      template:
        src: keepalived.conf.j2
        dest: /root/elastic_kibana_lab/keepalived/keepalived.conf
        mode: 0644


- name: Start service ha_kibana
  hosts: kibana
  become: yes
  tasks:
    - name: Stop service before start
      community.docker.docker_compose:
        project_src: /root/elastic_kibana_lab
        build: false
        remove_volumes: yes
        state : absent  # the same running docker-compose down

    - name: Start service
      community.docker.docker_compose:
        project_src: /root/elastic_kibana_lab
        build: false
        state : present # the same running docker-compose up

