- name: Hostname and folder
  hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: set hostname
      hostname:
        name: "{{ hostname }}"
    - name: Show host ip
      debug:
        msg: "{{ ansible_ssh_host }}"
    - name: Edit max vm ram
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes
    - name: Create /root/elastic_kibana_lab directory
      file:
        path: /root/elastic_kibana_lab/haproxy
        state: directory
        mode: 0755

    - name: Read current /etc/hosts file
      shell: cat /etc/hosts
      register: current_hosts
      changed_when: false

    - name: Update /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }} {{ hostvars[item]['ansible_hostname'] }}"
        insertafter: EOF
      loop: "{{ groups['all'] }}"
      when: "item not in current_hosts.stdout_lines"