- name: Install docker
  hosts: all
  become: yes
  vars:
    list_packages:
      - apt-transport-https
      - net-tools
      - ca-certificates
      - telnet
      - bridge-utils
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
    list_python_packages:
      - pyopenssl >= 23.2.0
      - requests==2.31.0 
      - docker==6.1.3
      - docker-compose

  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
    
    - name: Install requirement package
      apt:
        name: "{{ item }}"
        state: latest
      with_items: "{{ list_packages }}"

    - name: Add an apt key from url
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository into source list
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present 
  
    - name: Install docker
      apt: 
        name: "docker-ce"
        state: latest

    - name: Install docker python
      pip:
        name: "{{ item }}"
      with_items: "{{ list_python_packages }}"

    - name: Read current /etc/hosts file
      shell: cat /etc/hosts
      register: current_hosts
      changed_when: false

    - name: Update /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }} {{ hostvars[item]['ansible_hostname'] }}"
        insertafter: EOF
      loop: "{{ groups['all'] }}"
      when: "item not in current_hosts.stdout_lines"
      
